# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Create folder
      run: mkdir releases

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.x'

    - name: Install dependencies
      run: go get .
      
    - name: Build Linux
      run: go build -v -o ./releases/s1t9ledcontrol_linux_amd64

    - name: Build Windows
      run: GOOS=windows GOARCH=amd64 go build -v -o ./releases/s1t9ledcontrol_windows_amd64.exe

